spring:
   datasouece:
      user: pet_store
      passord: pet_store
      url: jdbc:mysql://localhost:3306:/pet_store
      
   jpa:
      hibernate:
         ddl-auto: create #update or create# then set to none to vaoid recreation 
      show-sql: true
      defer-datasource-initialization: true

   sql:
      init:
         mode: always #always or never#